WORKER_CITY_CONNECTOR = "data/workers/worker_city_connector.png"
WORKER_COMPETITION = "data/workers/worker_competition.png"
WORKER_PAX = "data/workers/worker_pax.png"
WORKER_PRESIDENT = "data/workers/worker_president.png"
WORKER_BUILD_DISCOUNT = "data/workers/worker_build_discount.png"
WORKER_FASTER_CONSTRUCTION = "data/workers/worker_faster_construction.png"
WORKER_WAGGONS_DISCOUNT = "data/workers/worker_waggons_discount.png"
