WORKER_ACCELERATION = "data/workers/worker_acceleration.png"
WORKER_ACCELERATION_SMALL = "data/workers/worker_acceleration_small.png"
WORKER_BUILD_DISCOUNT = "data/workers/worker_build_discount.png"
WORKER_BUILD_DISCOUNT_SMALL = "data/workers/worker_build_discount_small.png"
WORKER_CITY_CONNECTOR = "data/workers/worker_city_connector.png"
# TODO: WORKER_CITY_CONNECTOR SMALL
WORKER_COMPETITION = "data/workers/worker_competition.png"
WORKER_COMPETITION_SMALL = "data/workers/worker_competition_small.png"
WORKER_FASTER_BONUS = "data/workers/worker_faster_bonus.png"
# TODO: WORKER_FASTER_BONUS SMALL
WORKER_FASTER_CONSTRUCTION = "data/workers/worker_faster_construction.png"
WORKER_FASTER_CONSTRUCTION_SMALL = "data/workers/worker_faster_construction_small.png"
WORKER_GOLD_DISCOUNT = "data/workers/worker_gold_discount.png"
WORKER_GOLD_DISCOUNT_SMALL = "data/workers/worker_gold_discount_small.png"
WORKER_PAX = "data/workers/worker_pax.png"
WORKER_PAX_SMALL = "data/workers/worker_pax_small.png"
WORKER_PRESIDENT = "data/workers/worker_president.png"
WORKER_PRESIDENT_SMALL = "data/workers/worker_president_small.png"
WORKER_PRESTIGE_HOURLY = "data/workers/worker_prestige_hourly.png"
WORKER_PRESTIGE_HOURLY_SMALL = "data/workers/worker_prestige_hourly_small.png"
WORKER_PRESTIGE_INDUSTRY = "data/workers/worker_prestige_industry.png"
WORKER_PRESTIGE_INDUSTRY_SMALL = "data/workers/worker_prestige_industry_small.png"
WORKER_REDUCE_WT = "data/workers/worker_reduce_wt.png"
# TODO: WORKER_REDUCE_WT SMALL
WORKER_SCIENCE = "data/workers/worker_science.png"
# TODO: WORKER_SCIENCE SMALL
WORKER_SERVICE_DISCOUNT = "data/workers/worker_service_discount.png"
WORKER_SERVICE_DISCOUNT_SMALL = "data/workers/worker_service_discount_small.png"
WORKER_SPEED = "data/workers/worker_speed.png"
# TODO: WORKER_SPEED SMALL
WORKER_TRACK_DISCOUNT = "data/workers/worker_track_discount.png"
WORKER_TRACK_DISCOUNT_SMALL = "data/workers/worker_track_discount_small.png"
WORKER_WAGGONS_DISCOUNT = "data/workers/worker_waggons_discount.png"
WORKER_WAGGONS_DISCOUNT_SMALL = "data/workers/worker_waggons_discount_small.png"
